"""
Django settings for report project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3*v+j3(#kp8t&d9e5*fgi8qipzlwtgfo#qw40hs!2+_fvls_)4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '118.31.68.134', '42.194.237.4', 'potou.zhonghefull.com', '*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wechat',
    'reports',
    'health',
    'interface',
    'wage',
    'authorization',
    'invoice',
    'hospital',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'report.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'report.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'report',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'report',
            'USER': 'report',
            'PASSWORD': 'QQxuwen206420',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '/static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

USE_PROXY = True

API_HOST = 'http://58.62.175.49:8098/api/'
API_KEY = 'F2D8D966CD3D47788449C19D5EF2081B'
API_APP_ID = '60C90F3B796B41878B8D9C393E2B6329'
API_VERSION = 'V2.0.0'
API_SIGN_MODE = 'SM3'
API_ENCRYPT_MODE = 'SM4/ECB/ZeroBytePadding'
API_ORG_CODE = 'KGA00020100000014'
API_APP_RECORD_NO = '1301A0002QTHX0001'
API_NONCE_STR = '12345685217'

# APP_ID = 'wxd5191076ca1f7db7'
# APP_SECRET = '5a20659127d67fe81a9ea9a84dd3da8a'
APP_ID = 'wx896da0e215f91253'
APP_SECRET = '21df20f1f63944f9f0eeb65e5a5e6450'
TOKEN = 'JVWsgSgWG5Lu2z4jEE7OGRY18ixvJm4'

# 测试小程序
# WX_APP_ID = 'wxf44bb855d11bd5f6'
# WX_APP_SECRET = 'f946932fc5ab6ec1d95de1a4ef9fa72c'

# 坡头小程序
WX_APP_ID = 'wx761dedfc357039bc'
WX_APP_SECRET = 'd894cbe83769f622397350e9d780c9d4'

# 统计字段分隔符
STATISTICS_SPLIT_FLAG = '||'

# 首页标题
SIMPLEUI_HOME_TITLE = '快速开始'

# 服务器信息
SIMPLEUI_HOME_INFO = False

# 使用分析
SIMPLEUI_ANALYSIS = False

# 确定库是否会在数据导入中使用数据库事务，以确保安全。
IMPORT_EXPORT_USE_TRANSACTIONS = True

# 离线模式
SIMPLEUI_STATIC_OFFLINE = True
