# Generated by Django 3.0.8 on 2022-12-19 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRconfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=120, verbose_name='医院名称')),
                ('location', models.CharField(max_length=120, verbose_name='采样地点')),
                ('itemName', models.CharField(max_length=120, verbose_name='项目名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True, verbose_name='项目单价')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用二维码')),
                ('path_url', models.CharField(blank=True, max_length=200, verbose_name='链接地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '二维码配置',
                'verbose_name_plural': '二维码配置',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('patient', models.CharField(blank=True, max_length=120, null=True, verbose_name='就诊人')),
                ('idcard', models.CharField(blank=True, max_length=20, null=True, verbose_name='证件号码')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('number', models.CharField(blank=True, max_length=5, null=True, verbose_name='就诊人数')),
                ('amount', models.BigIntegerField(blank=True, default=0, verbose_name='收费单总金额')),
                ('orderNo', models.CharField(blank=True, max_length=32, unique=True, verbose_name='微信支付商户单号')),
                ('transactionID', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='微信支付交易单号')),
                ('prepayId', models.CharField(blank=True, max_length=100, null=True, verbose_name='预支付交易会话标识')),
                ('preTime', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单时间戳')),
                ('preNonce', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单随机字符串')),
                ('paySign', models.CharField(blank=True, max_length=200, null=True, verbose_name='支付签名')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='缴费的微信openid')),
                ('status', models.CharField(default='1', max_length=2, verbose_name='支付状态')),
                ('printf', models.CharField(default='0', max_length=2, verbose_name='打印标志')),
                ('expDate', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('timeEnd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='支付完成时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('print_time', models.DateTimeField(blank=True, default=None, help_text='打印时间', null=True, verbose_name='打印时间')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleic.QRconfig', verbose_name='支付场景二维码')),
            ],
            options={
                'verbose_name': '支付订单列表',
                'verbose_name_plural': '支付订单列表',
                'ordering': ('-create_time',),
            },
        ),
    ]
