# Generated by Django 3.0.8 on 2023-05-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrconfig',
            options={'ordering': ('-create_time',), 'verbose_name': '收费金额配置', 'verbose_name_plural': '收费金额配置'},
        ),
    ]
