# Generated by Django 3.0.8 on 2020-07-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('idCard', models.CharField(max_length=50, verbose_name='证件号')),
                ('open_id', models.CharField(max_length=50, verbose_name='微信openid')),
            ],
        ),
    ]
