# Generated by Django 3.0.8 on 2020-07-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='items',
            field=models.TextField(blank=True, default=[], null=True, verbose_name='检验项目'),
        ),
        migrations.AlterField(
            model_name='report',
            name='proposal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果'),
        ),
    ]
