# Generated by Django 3.0.8 on 2020-07-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200720_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='report',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='条码号'),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='送检科室'),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='送检医生'),
        ),
        migrations.AlterField(
            model_name='report',
            name='examiner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='检验者'),
        ),
        migrations.AlterField(
            model_name='report',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospital',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='送检医院'),
        ),
        migrations.AlterField(
            model_name='report',
            name='idCard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='证件号'),
        ),
        migrations.AlterField(
            model_name='report',
            name='inspection_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='检验日期'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报告日期'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='审核者'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='样本号'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='样本状态'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='样本类型'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sampling_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采样时间'),
        ),
    ]
