# Generated by Django 3.0.8 on 2021-07-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200722_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='N',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='N基因'),
        ),
        migrations.AddField(
            model_name='report',
            name='ORFlab',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ORFlab基因'),
        ),
        migrations.AddField(
            model_name='report',
            name='zjg',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='总结果'),
        ),
    ]
