# Generated by Django 3.0.8 on 2021-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210722_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sampling_agency',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='采样机构'),
        ),
    ]
