# Generated by Django 3.0.8 on 2021-07-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_sampling_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sampling_agency',
        ),
    ]
