# Generated by Django 3.0.8 on 2021-01-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32, unique=True, verbose_name='用户openid')),
                ('nickname', models.CharField(max_length=256, verbose_name='用户微信昵称')),
                ('username', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用户姓名')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否职工')),
            ],
            options={
                'verbose_name': '小程序用户列表',
                'verbose_name_plural': '小程序用户列表',
            },
        ),
    ]
