# Generated by Django 3.0.8 on 2021-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=256, verbose_name='用户微信头像'),
        ),
    ]
