# Generated by Django 3.0.8 on 2020-08-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=32, verbose_name='微信openid')),
                ('nickname', models.CharField(default='', max_length=256, verbose_name='微信昵称')),
                ('head_url', models.CharField(default='', max_length=200, verbose_name='微信头像')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='姓名')),
                ('id_code', models.CharField(default='', max_length=18, verbose_name='证件号码')),
                ('erhc_card_no', models.CharField(default='', max_length=200, verbose_name='电子健康码ID')),
                ('empi', models.CharField(default='', max_length=200, verbose_name='主索引ID')),
                ('qr_code', models.CharField(default='', max_length=200, verbose_name='静态二维码')),
                ('is_default', models.CharField(default='0', max_length=10, verbose_name='是否设置为默认卡')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='health.UserProfile', verbose_name='用户')),
            ],
        ),
    ]
