# Generated by Django 3.0.8 on 2020-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_untie',
            field=models.CharField(default='0', max_length=10, verbose_name='是否解绑，默认创建则绑定，1解绑'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='联系电话'),
        ),
    ]
