# Generated by Django 3.0.8 on 2020-09-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200902_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='medical',
            field=models.CharField(default='', max_length=32, verbose_name='诊疗卡号'),
        ),
    ]
