# Generated by Django 3.0.8 on 2022-03-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0003_usercard_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('idCard', models.CharField(default='', max_length=18, verbose_name='身份证号')),
                ('cardId', models.CharField(default='', max_length=50, verbose_name='诊疗卡号')),
                ('patientId', models.CharField(default='', max_length=50, verbose_name='唯一编号')),
                ('sex', models.CharField(default='', max_length=5, verbose_name='性别')),
                ('birth_dat', models.CharField(default='', max_length=20, verbose_name='生日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.UserProfile')),
            ],
            options={
                'verbose_name': '诊疗卡关联列表',
                'verbose_name_plural': '诊疗卡关联列表',
            },
        ),
    ]
