# Generated by Django 3.0.8 on 2022-03-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_list', models.CharField(default='', max_length=200, verbose_name='处方列表，字符串形式，以,隔开')),
                ('change', models.TextField(default='[]', verbose_name='费用明细, json.dumps() 后存入')),
                ('therapy', models.TextField(default='[]', verbose_name='治疗项目, json.dumps() 后存入')),
                ('status', models.CharField(default='0', max_length=5, verbose_name='处方状态')),
            ],
            options={
                'verbose_name': '处方保存',
                'verbose_name_plural': '处方保存',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(blank=True, max_length=32, unique=True, verbose_name='微信支付订单号与电子票据业务单号')),
                ('transactionID', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='微信支付订单号')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Recipe', verbose_name='订单所关联的处方')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
            },
        ),
    ]
