# Generated by Django 3.0.8 on 2022-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_payment_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_sum',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='处方金额'),
        ),
    ]
