# Generated by Django 3.0.8 on 2022-03-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_usercard_medical'),
        ('hospital', '0003_recipe_recipe_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.UserProfile'),
        ),
    ]
