# Generated by Django 3.0.8 on 2022-03-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20220328_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='1', max_length=2, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(default='1', max_length=5, verbose_name='处方状态'),
        ),
    ]
