# Generated by Django 3.0.8 on 2022-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20220329_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='缴费的微信openid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paySign',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='支付签名'),
        ),
        migrations.AddField(
            model_name='payment',
            name='preNonce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单随机字符串'),
        ),
        migrations.AddField(
            model_name='payment',
            name='preTime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单时间戳'),
        ),
        migrations.AddField(
            model_name='payment',
            name='prepayId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预支付交易会话标识'),
        ),
    ]
