# Generated by Django 3.0.8 on 2022-03-30 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20220330_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='过期时间'),
        ),
    ]
