# Generated by Django 3.0.8 on 2022-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_payment_expdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timeEnd',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='支付完成时间'),
        ),
    ]
