# Generated by Django 3.0.8 on 2022-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_payment_timeend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='patientId',
            field=models.CharField(default='', max_length=50, verbose_name='唯一编号'),
        ),
    ]
