# Generated by Django 3.0.8 on 2022-04-07 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_recipe_patientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(blank=True, max_length=32, unique=True, verbose_name='微信支付订单号与电子票据业务单号')),
                ('transactionID', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='微信支付订单号')),
                ('prepayId', models.CharField(blank=True, max_length=100, null=True, verbose_name='预支付交易会话标识')),
                ('preTime', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单时间戳')),
                ('preNonce', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一下单随机字符串')),
                ('paySign', models.CharField(blank=True, max_length=200, null=True, verbose_name='支付签名')),
                ('openid', models.CharField(blank=True, max_length=50, null=True, verbose_name='缴费的微信openid')),
                ('status', models.CharField(default='1', max_length=2, verbose_name='支付状态')),
                ('prStatus', models.CharField(default='1', max_length=2, verbose_name='打印状态')),
                ('expDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='过期时间')),
                ('timeEnd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='支付完成时间')),
            ],
            options={
                'verbose_name': '核酸缴费',
                'verbose_name_plural': '核酸缴费',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='notify',
            field=models.CharField(default='0', max_length=2, verbose_name='通知状态'),
        ),
    ]
