# Generated by Django 3.0.8 on 2022-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20220407_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleic',
            name='prStatus',
            field=models.CharField(default='0', max_length=2, verbose_name='打印状态'),
        ),
    ]
