# Generated by Django 3.0.8 on 2022-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20220408_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleic',
            name='idCard',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='nucleic',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='就诊人姓名'),
        ),
    ]
