# Generated by Django 3.0.8 on 2022-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20220408_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleic',
            name='code_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='支付二维码链接'),
        ),
    ]
