# Generated by Django 3.0.8 on 2021-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchaser_number',
            field=models.CharField(default='', max_length=32, verbose_name='受票方税号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_number',
            field=models.CharField(default='', max_length=32, verbose_name='销售方税号'),
        ),
    ]
