# Generated by Django 3.0.8 on 2021-01-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('invoice', '0002_auto_20210125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='authorization.User', verbose_name='提交人'),
        ),
    ]
