# Generated by Django 3.0.8 on 2021-01-26 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
