# Generated by Django 3.0.8 on 2021-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.CharField(default='', max_length=32, verbose_name='发票金额'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(default='', max_length=32, verbose_name='发票代码'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(default='', max_length=20, verbose_name='开票日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchaser',
            field=models.CharField(default='', max_length=256, verbose_name='受票方名称'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.CharField(default='', max_length=256, verbose_name='销售方名称'),
        ),
    ]
