# Generated by Django 3.0.8 on 2021-02-01 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0005_auto_20210128_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='操作内容')),
                ('edit_date', models.DateField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('edit_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='修改用户')),
            ],
        ),
    ]
