# Generated by Django 3.0.8 on 2021-02-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoicelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelog',
            options={'verbose_name': ('后台日志',), 'verbose_name_plural': ('后台日志',)},
        ),
    ]
