# Generated by Django 3.0.8 on 2021-02-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210201_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelog',
            options={'verbose_name': ('操作日志',), 'verbose_name_plural': ('操作日志',)},
        ),
    ]
