# Generated by Django 3.0.8 on 2023-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210201_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='update_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='', max_length=32, verbose_name='发票号码'),
        ),
    ]
