# Generated by Django 3.0.8 on 2023-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20230530_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='confirm_date',
            field=models.CharField(default='', max_length=20, verbose_name='修改状态日期'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirm_user',
            field=models.CharField(default='', max_length=20, verbose_name='修改状态用户'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='update_data',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='修改状态用户'),
        ),
    ]
