# Generated by Django 3.0.8 on 2023-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20230802_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchaser_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='录入用户'),
        ),
    ]
