# Generated by Django 3.0.8 on 2023-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20230802_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='confirm_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='修改状态日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='confirm_user',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='修改状态用户'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='录入用户'),
        ),
    ]
