# Generated by Django 3.0.8 on 2025-07-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_avatar'),
        ('invoice', '0015_auto_20250715_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='authorization.User', verbose_name='录入用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='录入用户'),
        ),
    ]
