# Generated by Django 3.0.8 on 2025-07-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20250715_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user_id',
        ),
    ]
