# Generated by Django 3.0.8 on 2025-07-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_avatar'),
        ('invoice', '0017_remove_invoice_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='authorization.User', verbose_name='录入用户'),
            preserve_default=False,
        ),
    ]
