# Generated by Django 3.0.8 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_auto_20250716_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='录入用户'),
        ),
    ]
