# Generated by Django 3.0.8 on 2020-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=30, verbose_name='身份证号码')),
                ('random_code', models.CharField(max_length=30, verbose_name='随机验证码')),
                ('content', models.CharField(max_length=255, verbose_name='工资条')),
            ],
        ),
    ]
