# Generated by Django 3.0.8 on 2020-10-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='content',
            field=models.TextField(default='', verbose_name='工资条'),
        ),
    ]
