# Generated by Django 3.0.8 on 2020-10-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage', '0002_auto_20201013_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='idCard',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='身份证号码'),
        ),
    ]
